Gatling plugin for carbynestack
carbynestack/caliper pull request #2
Opened 2023-05-22 08:42 UTC by juliangrewe-bosch

2023-06-13 11:46 UTC, strieflin requested changes
Finished first round of review. Some smaller changes are required. In addition, we have to wait for results of the open source scan.

2023-06-13 11:46 UTC, strieflin commented on .github/templates/sbom.ftl
> +</attributionReport>
Missing newlines at the end of multiple files indicate that you have not installed/used precommit. Please see https://github.com/carbynestack/carbynestack/blob/master/DEVELOPING.md for details on how to do this.

2023-06-13 11:46 UTC, strieflin commented on .mvn/wrapper/maven-wrapper.jar
This must be reflected in the SBOM as we are distributing this file. It seems to be Apache 2, so we need to include license and notice file (see https://maven.apache.org/wrapper/).

2023-06-13 11:46 UTC, strieflin commented on NOTICE.md
> +-  Grewe Julian
There is an extra whitespace here.

2023-06-13 11:46 UTC, strieflin commented on README.md
> +amphora client.
Amphora

2023-06-13 11:46 UTC, strieflin commented on README.md
> +actions are requests performed by a client that will be send during a
send -> sent

2023-06-13 11:46 UTC, strieflin commented on README.md
> +1. The common configuration to all Carbynestack-client requests, e.g. see
Carbynestack-client requests -> Carbynestack client requests

2023-06-13 11:46 UTC, strieflin commented on README.md
> +   the virtual users session
users -> user's

2023-06-13 11:46 UTC, strieflin commented on README.md
> +   `createSecret`-scenario
`createSecret`-scenario -> `createSecret` scenario

2023-06-13 11:46 UTC, strieflin commented on README.md
> +1. Attaching the `cs`-configuration matching the backend service configuration
`cs`-configuration -> `cs` configuration

2023-06-13 11:46 UTC, strieflin commented on .mvn/wrapper/maven-wrapper.jar
Alternatively, we can remove this binary file at it is anyway downloaded by mvnw[.cmd] script.

2023-06-13 11:46 UTC, strieflin commented on src/main/scala/org/gatling/plugin/carbynestack/protocol/CsProtocolBuilder.scala
> +}
Newline missing?

2023-06-13 11:46 UTC, strieflin commented on src/test/scala/CarbynestackSimulation.scala
> +    .endpoints(List("http://172.18.1.128/amphora", "http://172.18.2.128/amphora"))
This will only work for local kind-based deployments of CS. To allow for CI/CD-driven load testing, this should be replaced by configuration via a configuration management library (e.g. [Lightbend Config](https://github.com/lightbend/config), [PureConfig](https://www.baeldung.com/scala/pureconfig-load-config-files), and [ClearConfig](https://www.baeldung.com/scala/clearconfig)). This way on could read from a file or env variables.

2023-06-29 11:57 UTC, juliangrewe-bosch commented on .github/templates/sbom.ftl
> +</attributionReport>
done

2023-06-29 11:57 UTC, juliangrewe-bosch commented on .mvn/wrapper/maven-wrapper.jar
done

2023-06-29 11:57 UTC, juliangrewe-bosch commented on NOTICE.md
> +-  Grewe Julian
done

2023-06-29 11:57 UTC, juliangrewe-bosch commented on README.md
> +amphora client.
done

2023-06-29 11:58 UTC, juliangrewe-bosch commented on README.md
> +actions are requests performed by a client that will be send during a
done

2023-06-29 11:58 UTC, juliangrewe-bosch commented on README.md
> +   the virtual users session
done

2023-06-29 11:58 UTC, juliangrewe-bosch commented on README.md
> +   `createSecret`-scenario
done

2023-06-29 11:58 UTC, juliangrewe-bosch commented on README.md
> +1. Attaching the `cs`-configuration matching the backend service configuration
done

2023-06-29 11:58 UTC, juliangrewe-bosch commented on src/main/scala/org/gatling/plugin/carbynestack/protocol/CsProtocolBuilder.scala
> +}
done

2023-06-29 11:58 UTC, juliangrewe-bosch commented on src/test/scala/CarbynestackSimulation.scala
> +    .endpoints(List("http://172.18.1.128/amphora", "http://172.18.2.128/amphora"))
done

2023-06-29 13:11 UTC, merged